import type { CsnCustomAttributesConfig } from './types';

export const sapCsnAttributesConfig: CsnCustomAttributesConfig = {
    prefixStartsWith: '@',
    annotations: {
        '@EndUserText.label': { type: 'string', label: 'End User Text · Label' },
        '@EndUserText.heading': { type: 'string', label: 'End User Text · Heading' },
        '@EndUserText.quickInfo': { type: 'string', label: 'End User Text · Quick Info' },
        '@ObjectModel.modelingPattern': { type: 'object', label: 'Modeling Pattern' },
        '@ObjectModel.text.element': { type: 'array', label: 'Text Element' },
        '@ObjectModel.text.association': { type: 'object', label: 'Text Association' },
        '@ObjectModel.semanticKey': { type: 'array', label: 'Semantic Key' },
        '@ObjectModel.representativeKey': { type: 'object', label: 'Representative Key' },
        '@ObjectModel.compositionRoot': { type: 'boolean', label: 'Composition Root' },
        '@ObjectModel.supportedCapabilities': { type: 'array', label: 'Supported Capabilities' },
        '@ObjectModel.usageType.sizeCategory': { type: 'string', label: 'Usage Type · Size Category' },
        '@ObjectModel.foreignKey.association': { type: 'object', label: 'Foreign Key Association' },
        '@Consumption.valueHelpDefinition': { type: 'array', label: 'Value Help' },
        '@Consumption.hidden': { type: 'boolean', label: 'Hidden' },
        '@PersonalData.entitySemantics': { type: 'string', label: 'DPP · Entity Semantics' },
        '@PersonalData.dataSubjectRole': { type: 'string', label: 'DPP · Data Subject Role' },
        '@PersonalData.dataSubjectRoleDescription': { type: 'string', label: 'DPP · Data Subject Role Description' },
        '@PersonalData.fieldSemantics': { type: 'string', label: 'DPP · Field Semantics' },
        '@PersonalData.isPotentiallyPersonal': { type: 'boolean', label: 'DPP · Potentially Personal' },
        '@PersonalData.isPotentiallySensitive': { type: 'boolean', label: 'DPP · Potentially Sensitive' },
        '@Semantics.currencyCode': { type: 'boolean', label: 'Semantics · Currency Code' },
        '@Semantics.amount.currencyCode': { type: 'object', label: 'Semantics · Amount Currency' },
        '@Semantics.unitOfMeasure': { type: 'boolean', label: 'Semantics · Unit of Measure' },
        '@Semantics.quantity.unitOfMeasure': { type: 'object', label: 'Semantics · Quantity Unit' },
        '@Semantics.text': { type: 'boolean', label: 'Semantics · Text' },
        '@Semantics.uuid': { type: 'boolean', label: 'Semantics · UUID' },
        '@Semantics.language': { type: 'boolean', label: 'Semantics · Language' },
        '@API.element.releaseState': { type: 'string', label: 'API · Element Release State' },
        '@API.entity.releaseState': { type: 'string', label: 'API · Entity Release State' },
        '@ODM.entityName': { type: 'string', label: 'ODM · Entity Name' },
        '@ODM.oid': { type: 'string', label: 'ODM · OID' },
        '@ODM.oidReference.entityName': { type: 'string', label: 'ODM · OID Reference Entity' },
        '@Aggregation.default': { type: 'object', label: 'Default Aggregation' },
        '@EntityRelationship.entityType': { type: 'string', label: 'Entity Relationship · Type' },
        '@EntityRelationship.entityIds': { type: 'array', label: 'Entity Relationship · IDs' },
        '@EntityRelationship.propertyType': { type: 'string', label: 'Entity Relationship · Property Type' },
        '@EntityRelationship.compositeReferences': {
            type: 'array',
            label: 'Entity Relationship · Composite References',
        },
        '@EntityRelationship.reference': { type: 'array', label: 'Entity Relationship · Reference' },
        '@DataIntegration.dataUnavailable': { type: 'boolean', label: 'Data Integration · Unavailable' },
    },
};
