// AUTO-GENERATED by scripts/generate-overlay-code-styles.mjs — do not edit.
// Regenerate with: npm run generate:overlay-styles
//
// Maps shiki github-light token colors to the shared --ord-hljs-* theme tokens so overlay
// code blocks match the other renderers and follow the Theme Editor (light + dark).
// Derived from @shikijs/themes "github-light".
export default `
.overlay-root.ord-ui .ord-code-block .shiki span[style*="color:#6a737d" i] { color: var(--ord-hljs-comment) !important; }
.overlay-root.ord-ui .ord-code-block .shiki span[style*="color:#032f62" i] { color: var(--ord-hljs-string) !important; }
.overlay-root.ord-ui .ord-code-block .shiki span[style*="color:#d73a49" i] { color: var(--ord-hljs-keyword) !important; }
.overlay-root.ord-ui .ord-code-block .shiki span[style*="color:#22863a" i] { color: var(--ord-hljs-attr) !important; }
.overlay-root.ord-ui .ord-code-block .shiki span[style*="color:#005cc5" i] { color: var(--ord-hljs-number) !important; }
.overlay-root.ord-ui .ord-code-block .shiki span[style*="color:#6f42c1" i] { color: var(--ord-hljs-function) !important; }
.overlay-root.ord-ui .ord-code-block .shiki,
.overlay-root.ord-ui .ord-code-block .shiki span[style*="color:#24292e" i] { color: var(--ord-code-fg, var(--ord-hljs-punctuation)) !important; }
`;
