name: testing.yml
on:
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install NPM dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit Tests (Vitest)
        run: npm test

      - name: Build library
        run: npm run build

      - name: Install website dependencies
        working-directory: ./website
        run: npm ci

      - name: Build website
        working-directory: ./website
        run: npm run build
